sns-sdks/python-twitter

README.rst
pytwitter/api.py
testdata/apis/tweet/tweet_resp.json
testdata/apis/tweet/tweets_resp.json
tests/apis/test_tweets.py

Feat tweet

---

README.rst
pytwitter/api.py
pytwitter/models/ext.py
pytwitter/rate_limit.py
testdata/apis/timeline/timeline_mentions.json
testdata/apis/timeline/timeline_tweets.json
tests/apis/test_timelines.py
tests/test_rate_limit.py

Feat timeline

---

.github/workflows/test.yaml
README.rst
pyproject.toml
pytwitter/__init__.py
pytwitter/api.py
pytwitter/models/tweet.py
testdata/apis/searches/search_tweets_for_nyc.json
testdata/apis/searches/search_tweets_query.json
tests/apis/test_search.py

Feat search

---

README.rst
pytwitter/api.py
pytwitter/rate_limit.py
tests/apis/test_follows.py

Feat follow

---

pytwitter/models/media.py

fix(model): :sparkles: add url for media object.

---

pytwitter/api.py
testdata/apis/user/blocking_users_list_resp.json
tests/apis/test_follows.py
tests/apis/test_hidden_reply.py
tests/apis/test_tweets.py
tests/apis/test_users.py
tests/conftest.py

Feat blocking users

---

pytwitter/rate_limit.py

fix(ratelimit): :bug: ratelimt regex error

---

pytwitter/streaming.py
tests/streams/test_stream.py

feat(stream): :sparkles: add parameter for stream api

---

pytwitter/streaming.py

fix(data): :bug: fix sometimes response not have data in streaming

---

pytwitter/rate_limit.py
tests/test_rate_limit.py

Feat ratelimit

---

examples/search_streaming.py
pytwitter/streaming.py

Manage rules, had wrong type (`Set[Dict[...]]` instead of `Dict[...]`)
Also updated the example streaming_search

fix: manage_rules & example streaming

---

pytwitter/api.py

feat(tweets): :sparkles: Add fields for get list tweets

---

pytwitter/api.py

fix(token): :bug: fix token initial with generated by ouath flow.

---

README.rst
docs/docs/authorization.md
docs/docs/authorization_oauth2.md
docs/docs/index.md

Updates some links to Twitter docs and OAuth 2.0 references

docs: update references for OAuth 2.0 GA

---

pytwitter/models/media.py
pytwitter/models/place.py
pytwitter/models/space.py
pytwitter/models/tweet.py

Feat tweet model

---

.github/workflows/test.yaml
pytwitter/models/tweet.py
pytwitter/models/user.py

feat(fields): :sparkles: add new field for user and tweet

---

.github/workflows/test.yaml
pyproject.toml
pytwitter/streaming.py
tests/apis/test_search.py
tests/streams/test_auth.py

BREAKING CHANGE: 🧨 remove support for python 3.6

chore: 🤖 drop python3.6

---

pytwitter/api.py

ignore params if not pointed.
✅ Closes: #135

fix: 🐛 create tweet

---

pytwitter/models/tweet.py
pytwitter/models/user.py

feat(model): :sparkles: add new fields from twitter

---

pytwitter/api.py
pytwitter/models/ext.py
pytwitter/models/media.py
pytwitter/models/tweet.py
pytwitter/models/user.py
pytwitter/rate_limit.py
pytwitter/streaming.py
pytwitter/utils/convertors.py
pytwitter/utils/validators.py
tests/apis/test_auth.py
tests/apis/test_dm_events.py
tests/apis/test_media_upload.py
tests/apis/test_tweets.py
tests/streams/test_stream.py
tests/test_rate_limit.py
tests/test_utils.py

feat(users): :sparkles:  add new field dm-permission for user

---

pytwitter/models/user.py

feat(user): :sparkles: add field connection_status for user

---

pytwitter/models/media.py
pytwitter/models/tweet.py
pytwitter/models/user.py

feat(model): :sparkles: add new fields from twitter tweet

---

pyproject.toml

Update dataclasses-json version
